# Generated by Django 6.0.3 on 2026-04-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('score', models.IntegerField(blank=True, default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coding Progress',
                'verbose_name_plural': 'Coding Progress',
                'db_table': 'coding_progress',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField()),
                ('language', models.CharField(default='python', max_length=20)),
                ('run_type', models.CharField(choices=[('RUN', 'Run'), ('SUBMIT', 'Submit')], db_index=True, default='SUBMIT', max_length=10)),
                ('total_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('error', 'Error'), ('timeout', 'Timeout')], max_length=20)),
                ('score', models.IntegerField(blank=True, help_text='Optional score for this submission', null=True)),
                ('passed_count', models.IntegerField(blank=True, null=True)),
                ('failed_count', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('stderr', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('runtime_ms', models.IntegerField(blank=True, null=True)),
                ('attempt_no', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('details_json', models.JSONField(blank=True, default=list, help_text='Per-test results [{test_case_id, passed, output?, expected?}]. Teacher-only for hidden.')),
            ],
            options={
                'verbose_name': 'Coding Submission',
                'verbose_name_plural': 'Coding Submissions',
                'db_table': 'coding_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('starter_code', models.TextField(blank=True, default='')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('order_index', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coding Task',
                'verbose_name_plural': 'Coding Tasks',
                'db_table': 'coding_tasks',
                'ordering': ['order_index', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CodingTestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected', models.TextField()),
                ('explanation', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(blank=True, null=True)),
                ('is_sample', models.BooleanField(default=True, help_text='Used for Run (student preview); all cases used for Submit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coding Test Case',
                'verbose_name_plural': 'Coding Test Cases',
                'db_table': 'coding_test_cases',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CodingTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Coding Topic',
                'verbose_name_plural': 'Coding Topics',
                'db_table': 'coding_topics',
                'ordering': ['name'],
            },
        ),
    ]
