# Generated by Django 6.0.3 on 2026-04-04 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coding', '0001_initial'),
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='codingprogress',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_progress', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='codingsubmission',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coding_submissions', to='core.organization'),
        ),
        migrations.AddField(
            model_name='codingsubmission',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='coding_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codingtask',
            name='created_by',
            field=models.ForeignKey(db_column='created_by_id', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coding_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codingtask',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coding_tasks', to='core.organization'),
        ),
        migrations.AddField(
            model_name='codingsubmission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='coding.codingtask'),
        ),
        migrations.AddField(
            model_name='codingprogress',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='coding.codingtask'),
        ),
        migrations.AddField(
            model_name='codingtestcase',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='coding.codingtask'),
        ),
        migrations.AddField(
            model_name='codingtopic',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by_id', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_coding_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codingtopic',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coding_topics', to='core.organization'),
        ),
        migrations.AddField(
            model_name='codingtask',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='coding.codingtopic'),
        ),
        migrations.AddIndex(
            model_name='codingsubmission',
            index=models.Index(fields=['student', 'created_at'], name='coding_subm_student_f70301_idx'),
        ),
        migrations.AddIndex(
            model_name='codingsubmission',
            index=models.Index(fields=['student', 'task'], name='coding_subm_student_f900f3_idx'),
        ),
        migrations.AddIndex(
            model_name='codingsubmission',
            index=models.Index(fields=['task'], name='coding_subm_task_id_c463a8_idx'),
        ),
        migrations.AddIndex(
            model_name='codingsubmission',
            index=models.Index(fields=['created_at'], name='coding_subm_created_493471_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='codingprogress',
            unique_together={('student_profile', 'exercise')},
        ),
        migrations.AddIndex(
            model_name='codingtestcase',
            index=models.Index(fields=['task'], name='coding_test_task_id_072a11_idx'),
        ),
        migrations.AddIndex(
            model_name='codingtask',
            index=models.Index(fields=['topic'], name='coding_task_topic_i_e42f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='codingtask',
            index=models.Index(fields=['is_active'], name='coding_task_is_acti_60efe7_idx'),
        ),
        migrations.AddIndex(
            model_name='codingtask',
            index=models.Index(fields=['order_index'], name='coding_task_order_i_d7f221_idx'),
        ),
    ]
