# Generated by Django 6.0.2 on 2026-03-16 08:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('groups', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(db_column='payment_date')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank', 'Bank Transfer')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='paid', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('receipt_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sequence_number', models.IntegerField(blank=True, db_index=True, help_text='Sequential payment number (globally ordered by date)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by_id', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='groups.group')),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.organization')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['student_profile', 'payment_date'], name='payments_student_19c0c6_idx'), models.Index(fields=['group', 'payment_date'], name='payments_group_i_ff1343_idx')],
            },
        ),
    ]
