# Generated by Django 6.0.2 on 2026-03-16 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Profile',
                'verbose_name_plural': 'Parent Profiles',
                'db_table': 'parent_profiles',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, help_text='Class/Grade e.g. 10, 5A', max_length=50, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'db_table': 'student_profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
                'db_table': 'teacher_profiles',
            },
        ),
        migrations.CreateModel(
            name='ImportedCredentialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('CSV_IMPORT', 'CSV Import')], default='CSV_IMPORT', max_length=50)),
                ('student_full_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=254)),
                ('parent_email', models.EmailField(blank=True, default='', max_length=254)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('initial_password_encrypted', models.TextField(blank=True, null=True)),
                ('password_is_one_time', models.BooleanField(default=True)),
                ('password_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by_id', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_credential_records_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'role': 'parent'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_credential_as_parent', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='imported_credential_records_as_student', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imported Credential Record',
                'verbose_name_plural': 'Imported Credential Records',
                'db_table': 'imported_credential_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by'], name='imported_cr_created_9e7cf2_idx'), models.Index(fields=['student'], name='imported_cr_student_6aeced_idx')],
            },
        ),
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(limit_choices_to={'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_children', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent-Child',
                'verbose_name_plural': 'Parent-Child',
                'db_table': 'parent_student',
                'ordering': ['-created_at'],
                'unique_together': {('parent', 'student')},
            },
        ),
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Negative for debit (e.g. -12.50)', max_digits=10)),
                ('type', models.CharField(choices=[('lesson_debit', 'Dərs haqqı çıxılışı')], default='lesson_debit', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to='groups.group')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_transactions', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Balance Transaction',
                'verbose_name_plural': 'Balance Transactions',
                'db_table': 'balance_transactions',
                'ordering': ['-lesson_date', '-created_at'],
                'indexes': [models.Index(fields=['student_profile_id', 'lesson_date'], name='balance_tra_student_c896d9_idx'), models.Index(fields=['group_id', 'lesson_date'], name='balance_tra_group_i_5e4336_idx')],
                'constraints': [models.UniqueConstraint(fields=('student_profile', 'group', 'lesson_date', 'type'), name='unique_student_group_lesson_type')],
            },
        ),
        migrations.CreateModel(
            name='BalanceLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date of the transaction')),
                ('amount_delta', models.DecimalField(decimal_places=2, help_text='Negative for charges, positive for topups', max_digits=10)),
                ('reason', models.CharField(choices=[('LESSON_CHARGE', 'Lesson Charge'), ('TOPUP', 'Top-up'), ('MANUAL', 'Manual Adjustment')], db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balance_ledger_entries', to='groups.group')),
                ('student_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_ledger_entries', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Balance Ledger Entry',
                'verbose_name_plural': 'Balance Ledger Entries',
                'db_table': 'balance_ledger',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['student_profile', 'date'], name='balance_led_student_4cef6f_idx'), models.Index(fields=['group', 'date'], name='balance_led_group_i_b530d7_idx')],
                'constraints': [models.UniqueConstraint(fields=('student_profile', 'group', 'date', 'reason'), name='unique_student_group_date_reason')],
            },
        ),
    ]
