# Generated by Django 6.0.2 on 2026-03-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balanceledger',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Human-readable line for history (e.g. Dərs iştirakı - 2025-03-24)', max_length=255),
        ),
    ]
