"""
Teacher API URLs
"""
from django.urls import path
from ..views.teacher import (
    teacher_stats_view,
    teacher_students_view,
    teacher_student_restore_view,
    teacher_groups_view,
    teacher_group_students_view,
    teacher_move_student_view,
    teacher_payments_view,
    teacher_notifications_low_balance_view,
    teacher_impersonate_student_view,
    teacher_stop_impersonation_view,
)
from ..views.archive import (
    archive_payments_view,
    archive_groups_view,
    archive_students_view,
    restore_payment_view,
    restore_group_view,
)
from attendance.views.teacher import (
    teacher_attendance_grid_view,
    teacher_attendance_update_view,
    attendance_group_daily_view,
    attendance_save_view,
    attendance_group_monthly_view,
    attendance_student_daily_view,
    attendance_grid_new_view,
    attendance_bulk_upsert_view,
    attendance_bulk_delete_view,
    attendance_monthly_new_view,
    attendance_mark_all_present_view,
    lesson_finalize_view,
    lesson_unlock_view,
)
from coding.views.archive import (
    archive_coding_topics_view,
    archive_coding_tasks_view,
    restore_coding_topic_view,
    restore_coding_task_view,
    hard_delete_coding_topic_view,
    hard_delete_coding_task_view,
)
from coding.views.teacher import (
    teacher_coding_list_view,
    teacher_coding_detail_view,
    teacher_coding_import_json_view,
    teacher_coding_export_json_view,
    teacher_coding_monitor_view,
    teacher_coding_testcases_list_view,
    teacher_coding_testcase_detail_view,
    teacher_coding_topics_view,
    teacher_coding_topic_delete_view,
    teacher_coding_submissions_list_view,
    teacher_coding_submission_detail_view,
    teacher_student_submissions_view,
)
from tests.views.teacher import teacher_tests_list_view, teacher_test_result_create_view
from tests.views.archive import (
    archive_question_topics_view,
    archive_questions_view,
    archive_exams_view,
    archive_pdfs_view,
    restore_question_topic_view,
    restore_question_view,
    restore_exam_view,
    restore_pdf_view,
    hard_delete_question_topic_view,
    hard_delete_question_view,
    hard_delete_exam_view,
    hard_delete_pdf_view,
    bulk_delete_exams_view,
    bulk_delete_questions_view,
    bulk_delete_pdfs_view,
)
from tests.views.exams import (
    teacher_question_topics_view,
    teacher_question_topic_delete_view,
    teacher_questions_view,
    teacher_questions_bulk_delete_view,
    teacher_question_detail_view,
    teacher_exams_view,
    teacher_exam_detail_view,
    teacher_exam_activate_view,
    teacher_exam_add_question_view,
    teacher_exam_remove_question_view,
    teacher_exam_assign_groups_view,
    teacher_exam_start_now_view,
    teacher_exam_stop_view,
    teacher_exam_create_run_view,
    teacher_exam_runs_list_view,
    teacher_active_runs_list_view,
    teacher_finished_runs_list_view,
    teacher_run_attempts_view,
    teacher_run_reset_student_view,
    teacher_run_update_view,
    teacher_run_stop_view,
    teacher_run_history_delete_view,
    teacher_run_publish_view,
    teacher_exam_attempts_view,
    teacher_grading_attempts_view,
    teacher_exam_attempts_cleanup_view,
    teacher_exam_reset_student_view,
    teacher_exam_group_publish_view,
    teacher_exam_group_unpublish_view,
    teacher_exam_publish_all_view,
    teacher_attempt_detail_view,
    teacher_attempt_grade_view,
    teacher_attempt_publish_view,
    teacher_attempt_restart_view,
    teacher_attempt_continue_view,
    teacher_attempt_cancel_view,
    teacher_attempt_reopen_view,
    teacher_attempt_result_session_delete_view,
    teacher_pdfs_view,
    teacher_pdf_detail_view,
)
from students.views.bulk_import import (
    bulk_import_students_view,
    bulk_import_preview_view,
    bulk_import_confirm_view,
)
from students.views.bulk_import_users import (
    bulk_import_users_view,
    bulk_import_template_csv_view,
)
from students.views.credentials import (
    credentials_list_view,
    credentials_reveal_view,
    credentials_export_view,
    user_reveal_password_view,
    user_reset_password_view,
)

app_name = 'teacher'

urlpatterns = [
    path('stats', teacher_stats_view, name='stats'),
    path('students', teacher_students_view, name='students-list'),
    path('students/<int:pk>', teacher_students_view, name='students-detail'),
    path('students/<int:pk>/restore', teacher_student_restore_view, name='students-restore'),
    path('students/<int:pk>/hard', teacher_students_view, name='students-hard-delete'),
    path('impersonate/<int:student_id>', teacher_impersonate_student_view, name='impersonate-student'),
    path('stop-impersonation', teacher_stop_impersonation_view, name='stop-impersonation'),
    path('groups', teacher_groups_view, name='groups-list'),
    path('groups/<int:pk>/restore', restore_group_view, name='restore-group'),
    path('groups/<int:pk>', teacher_groups_view, name='groups-detail'),
    path('groups/<int:group_id>/students', teacher_group_students_view, name='group-students-add'),
    path('groups/<int:group_id>/students/<int:student_id>', teacher_group_students_view, name='group-students-remove'),
    path('groups/move-student', teacher_move_student_view, name='move-student'),
    path('notifications/low-balance', teacher_notifications_low_balance_view, name='notifications-low-balance'),
    path('payments', teacher_payments_view, name='payments-list'),
    path('payments/<int:pk>/restore', restore_payment_view, name='restore-payment'),
    path('payments/<int:pk>', teacher_payments_view, name='payments-detail'),
    path('attendance', teacher_attendance_grid_view, name='attendance-grid'),
    path('attendance/grid', attendance_grid_new_view, name='attendance-grid-new'),
    path('attendance/bulk-upsert', attendance_bulk_upsert_view, name='attendance-bulk-upsert'),
    path('attendance/bulk-delete', attendance_bulk_delete_view, name='attendance-bulk-delete'),
    path('attendance/monthly', attendance_monthly_new_view, name='attendance-monthly-new'),
    path('attendance/mark-all-present', attendance_mark_all_present_view, name='attendance-mark-all-present'),
    path('attendance/update', teacher_attendance_update_view, name='attendance-update'),
    path('attendance/group/<int:group_id>/daily', attendance_group_daily_view, name='attendance-daily'),
    path('attendance/save', attendance_save_view, name='attendance-save'),
    path('attendance/group/<int:group_id>/monthly', attendance_group_monthly_view, name='attendance-monthly'),
    path('attendance/group/<int:group_id>/student/<int:student_id>/daily', attendance_student_daily_view, name='attendance-student-daily'),
    path('lessons/finalize', lesson_finalize_view, name='lesson-finalize'),
    path('lessons/unlock', lesson_unlock_view, name='lesson-unlock'),
    path('archive/coding-topics', archive_coding_topics_view, name='archive-coding-topics'),
    path('archive/coding-tasks', archive_coding_tasks_view, name='archive-coding-tasks'),
    path('coding/topics', teacher_coding_topics_view, name='coding-topics'),
    path('coding/topics/<int:pk>', teacher_coding_topic_delete_view, name='coding-topic-delete'),
    path('coding/topics/<int:pk>/restore', restore_coding_topic_view, name='coding-topic-restore'),
    path('coding/topics/<int:pk>/hard-delete', hard_delete_coding_topic_view, name='coding-topic-hard-delete'),
    path('coding', teacher_coding_list_view, name='coding-list'),
    path('coding/import-json', teacher_coding_import_json_view, name='coding-import-json'),
    path('coding/export-json', teacher_coding_export_json_view, name='coding-export-json'),
    path('coding/<int:pk>', teacher_coding_detail_view, name='coding-detail'),
    path('coding/<int:pk>/restore', restore_coding_task_view, name='coding-task-restore'),
    path('coding/<int:pk>/hard-delete', hard_delete_coding_task_view, name='coding-task-hard-delete'),
    path('coding/<int:pk>/testcases', teacher_coding_testcases_list_view, name='coding-testcases'),
    path('coding/testcases/<int:caseId>', teacher_coding_testcase_detail_view, name='coding-testcase-detail'),
    path('coding-monitor', teacher_coding_monitor_view, name='coding-monitor'),
    path('coding/submissions', teacher_coding_submissions_list_view, name='coding-submissions'),
    path('coding/submissions/<int:pk>', teacher_coding_submission_detail_view, name='coding-submission-detail'),
    path('coding/student/<int:student_id>/submissions', teacher_student_submissions_view, name='student-submissions'),
    path('tests', teacher_tests_list_view, name='tests-list'),
    path('test-results', teacher_test_result_create_view, name='test-results-create'),
    path('archive/question-topics', archive_question_topics_view, name='archive-question-topics'),
    path('archive/questions', archive_questions_view, name='archive-questions'),
    path('archive/exams', archive_exams_view, name='archive-exams'),
    path('archive/pdfs', archive_pdfs_view, name='archive-pdfs'),
    path('archive/payments', archive_payments_view, name='archive-payments'),
    path('archive/groups', archive_groups_view, name='archive-groups'),
    path('archive/students', archive_students_view, name='archive-students'),
    path('question-topics', teacher_question_topics_view, name='question-topics'),
    path('question-topics/<int:pk>', teacher_question_topic_delete_view, name='question-topic-delete'),
    path('question-topics/<int:pk>/restore', restore_question_topic_view, name='question-topic-restore'),
    path('question-topics/<int:pk>/hard-delete', hard_delete_question_topic_view, name='question-topic-hard-delete'),
    path('questions', teacher_questions_view, name='questions'),
    path('questions/bulk-delete', teacher_questions_bulk_delete_view, name='questions-bulk-delete'),
    path('questions/<int:pk>', teacher_question_detail_view, name='question-detail'),
    path('questions/<int:pk>/restore', restore_question_view, name='question-restore'),
    path('questions/<int:pk>/hard-delete', hard_delete_question_view, name='question-hard-delete'),
    path('exams', teacher_exams_view, name='exams'),
    path('exams/<int:pk>', teacher_exam_detail_view, name='exam-detail'),
    path('exams/<int:pk>/activate', teacher_exam_activate_view, name='exam-activate'),
    path('exams/<int:pk>/restore', restore_exam_view, name='exam-restore'),
    path('exams/<int:pk>/hard-delete', hard_delete_exam_view, name='exam-hard-delete'),
    path('exams/<int:exam_id>/questions', teacher_exam_add_question_view, name='exam-add-question'),
    path('exams/<int:exam_id>/questions/<int:question_id>', teacher_exam_remove_question_view, name='exam-remove-question'),
    path('exams/<int:exam_id>/assign', teacher_exam_assign_groups_view, name='exam-assign-groups'),
    path('exams/<int:exam_id>/start-now', teacher_exam_start_now_view, name='exam-start-now'),
    path('exams/<int:exam_id>/stop', teacher_exam_stop_view, name='exam-stop'),
    path('exams/<int:exam_id>/create-run', teacher_exam_create_run_view, name='exam-create-run'),
    path('exams/<int:exam_id>/runs', teacher_exam_runs_list_view, name='exam-runs'),
    path('active-runs', teacher_active_runs_list_view, name='active-runs'),
    path('finished-runs', teacher_finished_runs_list_view, name='finished-runs'),
    path('runs/<int:run_id>/attempts', teacher_run_attempts_view, name='run-attempts'),
    path('runs/<int:run_id>/reset-student', teacher_run_reset_student_view, name='run-reset-student'),
    path('runs/<int:run_id>/stop', teacher_run_stop_view, name='run-stop'),
    path('runs/<int:run_id>/history-delete', teacher_run_history_delete_view, name='run-history-delete'),
    path('runs/<int:run_id>/publish', teacher_run_publish_view, name='run-publish'),
    path('runs/<int:run_id>', teacher_run_update_view, name='run-update'),
    path('grading/attempts', teacher_grading_attempts_view, name='grading-attempts'),
    path('exams/<int:exam_id>/attempts', teacher_exam_attempts_view, name='exam-attempts'),
    path('exams/<int:exam_id>/attempts/cleanup', teacher_exam_attempts_cleanup_view, name='exam-attempts-cleanup'),
    path('exams/<int:exam_id>/reset-student', teacher_exam_reset_student_view, name='exam-reset-student'),
    path('exams/<int:exam_id>/publish-all', teacher_exam_publish_all_view, name='exam-publish-all'),
    path('exams/<int:exam_id>/groups/<int:group_id>/publish', teacher_exam_group_publish_view, name='exam-group-publish'),
    path('exams/<int:exam_id>/groups/<int:group_id>/unpublish', teacher_exam_group_unpublish_view, name='exam-group-unpublish'),
    path('attempts/<int:attempt_id>', teacher_attempt_detail_view, name='attempt-detail'),
    path('attempts/<int:attempt_id>/grade', teacher_attempt_grade_view, name='attempt-grade'),
    path('attempts/<int:attempt_id>/publish', teacher_attempt_publish_view, name='attempt-publish'),
    path('attempts/<int:attempt_id>/restart', teacher_attempt_restart_view, name='attempt-restart'),
    path('attempts/<int:attempt_id>/continue', teacher_attempt_continue_view, name='attempt-continue'),
    path('attempts/<int:attempt_id>/cancel', teacher_attempt_cancel_view, name='attempt-cancel'),
    path('attempts/<int:attempt_id>/reopen', teacher_attempt_reopen_view, name='attempt-reopen'),
    path('attempts/<int:attempt_id>/result-session-delete', teacher_attempt_result_session_delete_view, name='attempt-result-session-delete'),
    path('pdfs', teacher_pdfs_view, name='pdfs'),
    path('pdfs/<int:pk>', teacher_pdf_detail_view, name='pdf-detail'),
    path('pdfs/<int:pk>/restore', restore_pdf_view, name='pdf-restore'),
    path('pdfs/<int:pk>/hard-delete', hard_delete_pdf_view, name='pdf-hard-delete'),
    path('archive/exams/bulk-delete', bulk_delete_exams_view, name='bulk-delete-exams'),
    path('archive/questions/bulk-delete', bulk_delete_questions_view, name='bulk-delete-questions'),
    path('archive/pdfs/bulk-delete', bulk_delete_pdfs_view, name='bulk-delete-pdfs'),
    path('bulk-import', bulk_import_students_view, name='bulk-import'),
    path('bulk-import/preview', bulk_import_preview_view, name='bulk-import-preview'),
    path('bulk-import/confirm', bulk_import_confirm_view, name='bulk-import-confirm'),
    path('bulk-import/users', bulk_import_users_view, name='bulk-import-users'),
    path('bulk-import/template-csv', bulk_import_template_csv_view, name='bulk-import-template-csv'),
    path('users/<int:user_id>/reveal-password', user_reveal_password_view, name='user-reveal-password'),
    path('users/<int:user_id>/reset-password', user_reset_password_view, name='user-reset-password'),
    path('credentials', credentials_list_view, name='credentials-list'),
    path('credentials/export.csv', credentials_export_view, name='credentials-export'),
    path('credentials/<int:pk>/reveal', credentials_reveal_view, name='credentials-reveal'),
]
