# Generated by Django 6.0.3 on 2026-04-04 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=255)),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='e.g. [1,2,3,4]; Mon=1..Sun=7')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('display_name_is_manual', models.BooleanField(default=False, help_text='If True, do not auto-overwrite display_name')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(blank=True, default=0, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Aylıq haqq (real AZN)', max_digits=10, null=True)),
                ('monthly_lessons_count', models.PositiveIntegerField(default=8, help_text='Ayda dərs sayı; per_lesson_fee = monthly_fee / monthly_lessons_count')),
                ('created_by', models.ForeignKey(db_column='teacher_id', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='core.organization')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'db_table': 'groups',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroupStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_students', to='groups.group')),
                ('organization', models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_memberships', to='core.organization')),
            ],
            options={
                'verbose_name': 'Group Student',
                'verbose_name_plural': 'Group Students',
                'db_table': 'group_students',
                'ordering': ['-joined_at'],
            },
        ),
    ]
