# Generated by Django 6.0.3 on 2026-04-04 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupstudent',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='students.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='groupstudent',
            unique_together={('group', 'student_profile')},
        ),
    ]
