# Generated by Django 6.0.2 on 2026-03-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattemptcanvas',
            name='canvas_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
