# Generated by Django 6.0.2 on 2026-03-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_add_canvas_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrun',
            name='published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='examrun',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
