# Generated by Django 6.0.2 on 2026-03-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_add_examrun_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='examrun',
            name='teacher_graded',
            field=models.BooleanField(db_index=True, default=False, help_text='Teacher has finished grading this run; remove from Yoxlama queue'),
        ),
    ]
