# Generated by Django 6.0.2 on 2026-03-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_add_examrun_teacher_graded'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/%Y/%m/'),
        ),
    ]
