# Generated by Django 6.0.2 on 2026-03-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_examrunstudent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='examrunstudent',
            new_name='exam_run_st_run_id_b2a7db_idx',
            old_name='exam_run_st_run_id_2d4163_idx',
        ),
        migrations.RenameIndex(
            model_name='examrunstudent',
            new_name='exam_run_st_student_bc074c_idx',
            old_name='exam_run_st_student_93dbfc_idx',
        ),
    ]
