# Generated by Django 6.0.2 on 2026-03-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_question_short_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='session_revision',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Incremented on teacher hard-restart; student clients poll to leave stale UI.'),
        ),
        migrations.AddField(
            model_name='examrun',
            name='teacher_unlocked_at',
            field=models.DateTimeField(blank=True, help_text='Set when teacher uses Continue (Davam et) so student UI can toast.', null=True),
        ),
    ]
