# Generated by Django 6.0.3 on 2026-04-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField(db_column='lesson_date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=20)),
                ('entry_state', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_name_snapshot', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'attendance_records',
                'ordering': ['-lesson_date', 'student_profile'],
            },
        ),
        migrations.CreateModel(
            name='GroupLessonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Group Lesson Session',
                'verbose_name_plural': 'Group Lesson Sessions',
                'db_table': 'group_lesson_sessions',
            },
        ),
        migrations.CreateModel(
            name='LessonHeld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Date the lesson was held')),
                ('is_finalized', models.BooleanField(db_index=True, default=True, help_text='Whether lesson is finalized (locked for editing)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lesson Held',
                'verbose_name_plural': 'Lessons Held',
                'db_table': 'lessons_held',
            },
        ),
    ]
