# Generated by Django 6.0.3 on 2026-04-04 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('core', '0001_initial'),
        ('groups', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='groups.group'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='marked_by',
            field=models.ForeignKey(blank=True, db_column='marked_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='core.organization'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='grouplessonsession',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_sessions', to='groups.group'),
        ),
        migrations.AddField(
            model_name='lessonheld',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons_held_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lessonheld',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_held', to='groups.group'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student_profile', 'lesson_date'], name='attendance__student_c0b486_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['group', 'lesson_date'], name='attendance__group_lesson_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['lesson_date'], name='attendance__lesson__b1fc87_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('student_profile', 'group', 'lesson_date'), name='unique_student_group_lesson_date'),
        ),
        migrations.AddIndex(
            model_name='grouplessonsession',
            index=models.Index(fields=['group_id', 'lesson_date'], name='group_lesso_group_i_66b92c_idx'),
        ),
        migrations.AddConstraint(
            model_name='grouplessonsession',
            constraint=models.UniqueConstraint(fields=('group', 'lesson_date'), name='unique_group_lesson_date'),
        ),
        migrations.AddIndex(
            model_name='lessonheld',
            index=models.Index(fields=['group_id', 'date'], name='lessons_hel_group_i_27c401_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonheld',
            index=models.Index(fields=['date'], name='lessons_hel_date_9a74c2_idx'),
        ),
        migrations.AddConstraint(
            model_name='lessonheld',
            constraint=models.UniqueConstraint(fields=('group', 'date'), name='unique_group_lesson_held_date'),
        ),
    ]
